# Generated by Django 4.2.3 on 2023-07-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='data/img')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
            ],
        ),
    ]
